services:
  wp:
    image: wordpress:6.8.1-php8.4
    ports:
      - 8080:80
    volumes:
      - ./wp:/var/www/html # WordPress root
      - ./dmg-post-finder:/var/www/html/wp-content/plugins/dmg-post-finder # Our new plugin
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: true
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db
      - wp

  db:
    image: mariadb:latest
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - 8081:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data: