services:
  wp:
    container_name: dmg-wp
    image: wordpress:6.8.1-php8.4
    ports:
      - 8080:80
    volumes:
      - ./wp:/var/www/html # WordPress root
      - ./dmg-post-finder:/var/www/html/wp-content/plugins/dmg-post-finder # Our new plugin
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_LOG', '1' );
        define( 'WP_DEBUG_DISPLAY', '0' );
        define( 'SCRIPT_DEBUG', '1' );
        define( 'WP_DEBUG_LOG_FILE', '/var/www/html/wp-content/debug.log' );
    depends_on:
      - db
    links:
      - db

  db:
    container_name: dmg-db
    image: mariadb:latest
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    ports:
      - 8081:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
